name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test imports and DB init
        run: |
          python - <<'PY'
          from database import init_db, SessionLocal
          from recommendation_engine import EnhancedRecommendationEngine
          from main import app
          
          # Initialize DB and run a tiny query
          init_db()
          db = SessionLocal()
          try:
              engine = EnhancedRecommendationEngine(db)
              popular = engine.get_popular_products(limit=3)
              print({"popular_count": len(popular)})
          finally:
              db.close()
          print("SMOKE TEST OK")
          PY

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: qwipo-backend:ci
